In [29]:
import pandas as pd

In [46]:
df=pd.read_csv("sentiment_analysis.csv")

In [47]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [48]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [49]:
df.drop_duplicates(inplace=True)

In [50]:
df.shape

(49582, 2)

# preprocessing

# 1 converting to lowercase

In [51]:
df["review"]=df["review"].str.lower()

In [52]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# 2 remove url

In [53]:
import re
def remove_urls(text):
    text=re.sub(r"http\S+","",text)
    return text
df["review"]=df["review"].apply(remove_urls)

# 3 remove punctuations

In [54]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
df["review"]=df["review"].apply(remove_punctuations)

# 4 remove html

In [55]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text)
    return text
df["review"]=df["review"].apply(remove_html)

# 5 remove stopwords

In [56]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ranas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ranas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ranas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [57]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [60]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")
    for word in tokens:
        if word in stop_words:
           text=text.replace(word,"")
    return text

In [63]:
df["review"]=df["review"].apply(remove_stopwords)

In [64]:
df.head()

                                              review sentiment
0  e    revewers  nte   wtchg  1 oz epoe   hooke ...  positive
1   wderful ltle prducti br br  filming technique...  positive
2   hugh h   werful w  pen me    h ummer weeken n...  positive
3  bcy   fly   e boy jke hk   zobe   cloe   pn  f...  negative
4  peer me love   i     vu unng film  wch mr mei ...  positive

# 6 stemming

In [66]:
# running=> run
# playing=> play
#using porterstemming
from nltk.stem import PorterStemmer

In [68]:
def stemming(text):
    ps=PorterStemmer()
    stemming_words=[]
    tokens=word_tokenize(text)
    for word in tokens:
        stemmed_tokens=ps.stem(word)
        stemming_words.append(stemmed_tokens)
    return " ".join(stemming_words)

In [69]:
df["review"]=df["review"].apply(stemming)

In [70]:
df.head()

                                              review sentiment
0  e revew nte wtchg 1 oz epo hook rght exctl hpp...  positive
1  wder ltle prducti br br film techniqu unssum l...  positive
2  hugh h wer w pen me h ummer weeken ng n r cne ...  positive
3  bci fli e boy jke hk zobe cloe pn fghg ebr br ...  negative
4  peer me love i vu unng film wch mr mei fer u v...  positive

# 7 encoding

In [72]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["sentiment"]=le.fit_transform(df["sentiment"])

In [74]:
y=df["sentiment"]

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(max_features=5000)
X=tf.fit_transform(df["review"])

In [78]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316102 stored elements and shape (49582, 5000)>

In [79]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316102 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3962)	0.07314282300609996
  (0, 4935)	0.14950938847188663
  (0, 3426)	0.4698640965354833
  (0, 1491)	0.16244209325938672
  (0, 2283)	0.07923919927127605
  (0, 3978)	0.15178703358489806
  (0, 1629)	0.09605370040119345
  (0, 2328)	0.059413310971479213
  (0, 264)	0.08228624418462524
  (0, 1935)	0.16942996486293824
  (0, 4314)	0.05899315405421301
  (0, 4166)	0.05729696611296147
  (0, 4709)	0.2770729449171833
  (0, 4201)	0.08362913949999684
  (0, 2065)	0.03483596838994734
  (0, 4215)	0.2641922463354714
  (0, 1940)	0.07943834322627065
  (0, 2199)	0.0901262901744208
  (0, 3802)	0.043113833333287284
  (0, 3816)	0.08133575442157247
  (0, 3924)	0.09368624090115052
  (0, 4125)	0.07568854099337527
  (0, 4204)	0.08005374587498516
  (0, 614)	0.0977245052147425
  (0, 4605)	0.06771933259930923
  :	:
  (49581, 3013)	0.6322832966347672
  (49581, 3600)	0.07708762613869068
  (49581, 256)	0.08283729185906373
  (49581, 4123)	0.09153434378227822
  (49581, 427)	0.06226178108370525
  (49581, 515)	0.10642698607162616
  (49581, 4632)	0.08094985102172797
  (49581, 2616)	0.13341204943087576
  (49581, 1505)	0.1205769318065429
  (49581, 2311)	0.10627919032226671
  (49581, 2656)	0.08997373475343341
  (49581, 4541)	0.12696239513563262
  (49581, 367)	0.1321628987820879
  (49581, 4880)	0.2404904575119017
  (49581, 4703)	0.13086508465005006
  (49581, 621)	0.1297007062963437
  (49581, 4742)	0.10285633187856055
  (49581, 1492)	0.12072046070109305
  (49581, 3948)	0.17366105732823034
  (49581, 2603)	0.17858909593995048
  (49581, 2343)	0.14429517003247952
  (49581, 523)	0.1262025996828523
  (49581, 4973)	0.15568356974471215
  (49581, 2087)	0.1760027848307958
  (49581, 3624)	0.1715216241299442

# datasets and dataloader

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [81]:
X_train.shape

(39665, 5000)

In [82]:
X_test.shape

(9917, 5000)

In [87]:
import torch 
from torch.utils.data import DataLoader,TensorDataset

In [85]:
X_train# xtrain is a sparse matrix so we have to convert it to the numpy array from sparse matrix as dataloader cannot use sparse matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2655143 stored elements and shape (39665, 5000)>

In [88]:
X_train=X_train.toarray()
X_test=X_test.toarray()

In [89]:
train_set=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)
test_set=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [90]:
train_loader=DataLoader(train_set,shuffle=True,batch_size=64)
test_loader=DataLoader(test_set,shuffle=True,batch_size=64)

# build the rnn

In [93]:
import torch 
import torch.nn as nn
import torch.optim as optim

In [96]:
class RNN(nn.Module):
    def __init__(self,input_size,hidden_size=128,num_layers=1):
        super().__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers
        # RNN layer
        self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)
        # fully connected layer
        self.fc=nn.Linear(hidden_size,1)
    def forward(self,x):
        #optional=>(num of layer,batch size,hidden size)
        h0=torch.zeros(self.num_layers,x.size(0),self.hidden_size)
        out,_=self.rnn(x,h0)
        out=self.fc(out[:,-1,:])
        return out

In [97]:
input_size=X_train.shape[1]
model=RNN(input_size)
creterion=nn.BCELoss()
optimizer=optim.Adam(model.parameters())

## training the RNN

In [100]:
epochs=10
for epoch in range(epochs):
    model.train()
    for Xb,yb in train_loader:
        optimizer.zero_grad()
        Xb=Xb.unsqueeze(1)
        outputs=model(Xb)
        outputs=torch.sigmoid(outputs.squeeze())
        loss=creterion(outputs,yb)
        loss.backward()
        optimizer.step()
    print(f"epoch={epoch+1}/{epochs} loss is{loss.item()} ")

epoch=1/10 loss is0.31170493364334106
epoch=2/10 loss is0.31058886647224426
epoch=3/10 loss is0.48577767610549927
epoch=4/10 loss is0.21866269409656525
epoch=5/10 loss is0.37794193625450134
epoch=6/10 loss is0.28519946336746216
epoch=7/10 loss is0.3125384449958801
epoch=8/10 loss is0.28479254245758057
epoch=9/10 loss is0.28516918420791626
epoch=10/10 loss is0.2565867304801941

In [101]:
# evalution
model.eval()
with torch.no_grad():
    correct_val=0
    total_val=0
    for Xb,yb in test_loader:
         Xb=Xb.unsqueeze(1)
         outputs=model(Xb)
         predicted=(torch.sigmoid(outputs.squeeze())>0.5).float()
         total_val+=yb.size(0)
         correct_val+=(predicted==yb).sum().item()
    print(f"accuracy={correct_val/total_val}")

accuracy=0.8263587778562065